### ISSUE TITLE
Uncaught TypeError: application.addTweenManager is not a function

### ISSUE THREAD

**Issue by Byrniee** [playcanvas/playcanvas-tween#37] opened 2023-05-18 14:10 UTC
### Description
I'm getting the error "Uncaught TypeError: application.addTweenManager is not a function". 
I've tried rolling back to a known working commit but the error still occurs. Also happens on new projects.

Sample project: 
https://playcanvas.com/project/1077282

### Steps to Reproduce
1. Create a blank PlayCanvas project
2. Add the tween.js file
3. Hit Launch and check the Console output.

Tested on Chrome and Safari

**Comment by willeastcott** [comment] 2023-05-18 14:15
This was caused by a deployment we just made. We've rolled back. Can you confirm things are ok now?

**Comment by sagargirme** [comment] 2023-05-18 14:16
yes its working now

**Comment by sagargirme** [comment] 2023-05-19 11:20
again the issue started

**Comment by Byrniee** [comment] 2023-05-19 11:21
We're seeing it again too.

**Comment by Byrniee** [comment] 2023-05-19 11:27
@sagargirme The Tween Library just needs updating, see here:
https://forum.playcanvas.com/t/editor-v1-30-8-and-tween-library/31357

**Comment by willeastcott** [comment] 2023-05-22 13:45
Closing since the tween library just needs to be updated to latest.

**Closed by willeastcott** 2023-05-22 13:45 UTC
Labels: bug
